# -*- coding: utf-8 -*-
"""causal_description_impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbxHZdhKnBB-lTaY60JVkiQAm-Pd1HCk
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

# 1. Load the Data (Using Olist E-commerce Public Data)
# Assume we have products and their order history
products = pd.read_csv('olist_products_dataset.csv')
orders = pd.read_csv('olist_order_items_dataset.csv')

# 2. Feature Engineering & Defining the Funnel
# Calculate how many times each product was sold
sales_count = orders.groupby('product_id').size().reset_index(name='sales_volume')
df = products.merge(sales_count, on='product_id', how='left').fillna(0)

# Define Treatment (Z): Did the seller write a long description? (e.g., > 500 characters)
df['long_description'] = (df['product_description_lenght'] > 500).astype(int)

# Define Outcome (Y): Is this a high-converting/high-selling product? (> 5 sales)
df['high_sales'] = (df['sales_volume'] > 5).astype(int)

# Define Confounders (X): Things that affect BOTH description length and sales
# Example: heavier/larger items might need more description and cost more
df['product_weight_g'] = df['product_weight_g'].fillna(df['product_weight_g'].median())
df['product_photos_qty'] = df['product_photos_qty'].fillna(0)

X = df[['product_weight_g', 'product_photos_qty']]
Z = df['long_description']
Y = df['high_sales']

# 3. Estimate Propensity Scores
# Predict the probability of a product getting a long description based on its physical traits
log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X, Z)

# Extract the probabilities P(Z=1 | X)
df['propensity_score'] = log_reg.predict_proba(X)[:, 1]

# Prevent extreme weights by clipping propensity scores (e.g., between 0.05 and 0.95)
df['propensity_score'] = np.clip(df['propensity_score'], 0.05, 0.95)

# 4. Inverse Probability Weighting (IPW)
# Calculate weights to balance the treatment and control groups
# Weight = Z / PS + (1 - Z) / (1 - PS)
df['ipw_weight'] = (df['long_description'] / df['propensity_score']) + \
                   ((1 - df['long_description']) / (1 - df['propensity_score']))

# 5. Calculate Causal Impact using Weighted Least Squares (WLS)
# This model finds the true impact of the long description on sales, controlled for confounders
X_wls = sm.add_constant(df['long_description'])
wls_model = sm.WLS(Y, X_wls, weights=df['ipw_weight']).fit()

# Print the Executive Summary
print("--- Causal Inference Results ---")
print(wls_model.summary())

# Extract the specific causal uplift
uplift = wls_model.params['long_description']
p_value = wls_model.pvalues['long_description']

print("\n--- Business Takeaway ---")
if p_value < 0.05:
    print(f"Statistically Significant! A long description causes a {uplift*100:.2f}% increase in the probability of being a top-selling item.")
else:
    print("No causal impact found. Description length is likely a proxy for other seller behaviors, not a direct driver of sales.")